set_global_assignment -name IP_FILE ../src/custom_rtl/ptp_bridge_ip/tcam.ip
set_global_assignment -name IP_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/eth_f_tod.ip
set_global_assignment -name IP_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/eth_f_tod_sync.ip
set_global_assignment -name IP_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/eth_f_tod_10g.ip
set_global_assignment -name IP_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/eth_f_tod_sync_10g.ip
set_global_assignment -name IP_FILE ../src/ip/ptp_ed_issp.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/hssi_ss_25G/hssi_ss_25G.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_rx_dma/rx_dma_clock.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_rx_dma/rx_dma_ftile_clock.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_rx_dma/rx_dma_reset.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_rx_dma/rx_dma_csr.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_rx_dma/rx_dma_prefetcher.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_rx_dma/rx_dma_dispatcher.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_rx_dma/rx_dma_write_master.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_rx_dma/rx_dma_fifo_0.ip
set_global_assignment -name QSYS_FILE ../src/qsys/subsys_ftile_rx_dma.qsys
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_tx_dma/tx_dma_clock.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_tx_dma/tx_dma_ftile_clock.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_tx_dma/tx_dma_reset.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_tx_dma/tx_dma_csr.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_tx_dma/tx_dma_prefetcher.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_tx_dma/tx_dma_dispatcher.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_tx_dma/tx_dma_read_master.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_tx_dma/tx_dma_fifo_0.ip
set_global_assignment -name QSYS_FILE ../src/qsys/subsys_ftile_tx_dma.qsys
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/subsys_ftile_1588_csrclk.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/subsys_ftile_1588_reset.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/subsys_ftile_1588_ninitdone_reset.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/subsys_ftile_1588_csr.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/iopll_clk_avst_div2.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/qsfpdd_status_pio.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/ftile_debug_status_pio_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/subsys_ftile_1588_dmaclkout.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/subsys_ftile_1588_dmaclkout_reset.ip
set_global_assignment -name QSYS_FILE ../src/qsys/subsys_ftile_1588.qsys
set_global_assignment -name IP_FILE ../src/ip/qsys_top/clk_100.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/rst_in.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/user_rst_clkgate_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/sysid.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/fpga_m2ocm_pb.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/agilex_hps.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/emif_hps.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/emif_calbus_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/qsys_top_master_todclk_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/subsys_ftile_1588_o_pll_clk.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/master_tod_top_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/ftile_iopll_todsync_sampling.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/qsys_top_iopll_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/avst_axist_bridge_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/msgdma_ptp_subsys_8chs_ts_chs_compl_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/qsys_top_ninit_done.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/subsys_ftile_1588_avst_axist_bridge_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/hssi_ets_ts_adapter_0.ip
set_global_assignment -name IP_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/ghrd_f_mtod_master_pll.ip
set_global_assignment -name IP_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/ghrd_f_mtod_pps_pll.ip
set_global_assignment -name IP_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/ghrd_f_mtod_pps_pll_rcfg.ip
set_global_assignment -name IP_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/ghrd_f_master_tod.ip
set_global_assignment -name QSYS_FILE ../src/qsys/sys_manager.qsys
set_global_assignment -name QSYS_FILE ../src/qsys/hps_sub_sys.qsys
set_global_assignment -name QSYS_FILE ../src/qsys/dma_subsystem.qsys
set_global_assignment -name QSYS_FILE ../src/qsys/tod_slave_sub_system.qsys
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/oclk_pll_clock_bridge_0.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/dma_clk_out_bridge_0.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/dma_clk_100.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/dma_rst_100.ip
set_global_assignment -name IP_FILE ../src/ip/tod_slave_sub_system/tod_subsys_clk_100.ip
set_global_assignment -name IP_FILE ../src/ip/tod_slave_sub_system/tod_subsys_mtod_clk.ip
set_global_assignment -name IP_FILE ../src/ip/tod_slave_sub_system/tod_subsys_rst_100.ip
set_global_assignment -name IP_FILE ../src/ip/tod_slave_sub_system/port0_tod_stack_0.ip
set_global_assignment -name IP_FILE ../src/ip/tod_slave_sub_system/port_0_tod_stack.ip
set_global_assignment -name IP_FILE ../src/ip/tod_slave_sub_system/port_0_tod_stack_1.ip
set_global_assignment -name IP_FILE ../src/ip/tod_slave_sub_system/todsync_sample_plllock_split.ip
set_global_assignment -name IP_FILE ../src/ip/tod_slave_sub_system/master_tod_split.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/oclk_pll_port1.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/dma_ss_master.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_rx_dma/ftile_clk_reset.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/rx_dma_reset_bridge.ip
set_global_assignment -name IP_FILE ../src/ip/sys_manager/dma_subsys_port0_rx_dma_resetn.ip
set_global_assignment -name IP_FILE ../src/ip/sys_manager/dma_subsys_port1_rx_dma_resetn.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/rx_dma_reset_bridge_0.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/rx_dma_reset_bridge_1.ip
set_global_assignment -name QSYS_FILE ../src/qsys/master_tod_subsys.qsys
set_global_assignment -name IP_FILE ../src/ip/master_tod_subsys/mtod_subsys_clk100.ip
set_global_assignment -name IP_FILE ../src/ip/master_tod_subsys/mtod_subsys_rstn.ip
set_global_assignment -name IP_FILE ../src/ip/master_tod_subsys/mtod_subsys_pps_load_tod_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/axi4lite_rst_bdg.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/axi4lite_clk_bdg.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/o_p9_clk_pll.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/o_p9_clk_txdiv.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/o_p8_rec_divclk.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/o_p9_rec_divclk.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/o_p8_clk_div.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/o_p8_clk_pll.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/iopll_sample_clk.ip
set_global_assignment -name IP_FILE ../src/ip/sys_manager/dma_subsys_port1_rx_dma_resetn_0.ip
set_global_assignment -name IP_FILE ../src/ip/sys_manager/dma_subsys_port1_rx_dma_resetn_1.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/rx_dma_reset_bridge_4.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/rx_dma_reset_bridge_5.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/rx_dma_reset_bridge_2.ip
set_global_assignment -name IP_FILE ../src/ip/sys_manager/dma_subsys_port1_rx_dma_resetn_2.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/rx_dma_reset_bridge_3.ip
set_global_assignment -name IP_FILE ../src/ip/sys_manager/dma_subsys_port1_rx_dma_resetn_3.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/o_p1_clk_pll_1.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/o_p1_clk_pll_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/o_p1_clk_pll_3.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/o_p1_clk_pll_2.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/oclk_pll_port1_0.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/oclk_pll_port1_1.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/oclk_pll_port1_2.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/oclk_pll_port1_3.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/axi4lite_pktcli_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/axi4lite_pktcli_1.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/axi4lite_ptpb.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/axi4lite_hssi.ip
set_global_assignment -name IP_FILE ../src/ip/dma_subsystem/dma_subsystem_oclk_pll_port5_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/hps_sub_sys_agilex_axi_bridge_for_acp_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/qsys_top_reset_controller_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_ftile_1588/qsfpdd_ctrl_pio_0.ip
set_global_assignment -name QSYS_FILE ../src/qsys/qsys_top.qsys
