set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_igr_arb/ptp_bridge_ipbb_pref_rrarb.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dbg_components/ptp_bridge_tx_avmm_addr_chk.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dbg_components/ptp_bridge_rx_avmm_addr_chk.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_common/ptp_bridge_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_common/ptp_bridge_hdr_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/macsec_srd_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/components_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/axi4lite_if.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/ptp_bridge_tx_igr_wadj.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/ptp_bridge_rx_igr_wadj.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/egr_wadj_csr_intf.sv
set_global_assignment -name VERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/egr_wadj_csr.v
set_global_assignment -name VERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dbg_components/tx_dbg_csr.v
set_global_assignment -name VERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dbg_components/rx_dbg_csr.v
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dbg_components/ptp_bridge_tx_dbg_cntr_intf.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dbg_components/ptp_bridge_tx_dbg.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dbg_components/ptp_bridge_rx_dbg_cntr_intf.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dbg_components/ptp_bridge_rx_dbg.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dbg_components/ptp_bridge_dbg_cntr.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_subsys.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/eth_f_packet_client_csr_pkt_cnt.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/axi4lite2avmm_bridge.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/eth_f_packet_client_csr.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/eth_f_pkt_stat_counter.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/avmm_if.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/eth_f_pkt_gen_dyn_25G.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/eth_f_pkt_gen_dyn_100G.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/eth_f_packet_client_top_axi_adaptor.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/eth_f_packet_client_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/eth_f_packet_client_data_check_25G.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/eth_f_packet_client_data_check_100G.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/pkt_client/avst_data_merger.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/ptp_bridge_igr_wadj.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/ptp_bridge_egr_wadj.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/ptp_bridge_axi_wdj_lg2sm.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/igr_wadj_csr_intf.sv
set_global_assignment -name VERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/igr_wadj_csr.v
set_global_assignment -name VERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/igr_wadj_10G_csr.v
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_wadj/egr_wadj_seg_split.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_top/ptp_bridge_tx.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_top/ptp_bridge_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_top/ptp_bridge_rx.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_parse_class/ptp_bridge_parse_class.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_parse_class/parse_class_l2l3l4.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_parse_class/parse_class_igr_intf.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_misc/ptp_bridge_pipe_dly.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_misc/ptp_bridge_ipbb_sfw_fifo.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_misc/ptp_bridge_ipbb_sdc_fifo_inff.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_misc/ptp_bridge_axi_lt_avmm.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_misc/ptp_bridge_avmm_addr_chk.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_misc/ipbb_sfw_fifo.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_misc/ipbb_scfifo_inff.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_misc/ipbb_pipe.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_misc/ipbb_axi_lite_to_avmm_range_check_cdc.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_misc/ipbb_asyn_to_syn_rst.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_lkup/ptp_bridge_lkup.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_lkup/lkup_tcam_intf.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_lkup/lkup_ccm.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_igr_arb/ptp_bridge_igr_arb.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_igr_arb/ipbb_rrarb.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_igr_arb/ipbb_priority_rr.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_igr_arb/igr_arb_csr_intf.sv
set_global_assignment -name VERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_igr_arb/igr_arb_csr.v
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dmux/ptp_bridge_dma_ts_dmux.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dmux/ptp_bridge_dma_rx_dmux.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dmux/dma_rx_dmux_csr_intf.sv
set_global_assignment -name VERILOG_FILE ../src/custom_rtl/ptp_bridge_ip/ptp_bridge_dmux/dma_rx_dmux_csr.v
set_global_assignment -name VERILOG_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/altera_std_syncronizer.v
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/eth_f_data_synchronizer.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/exd_std_synchronizer.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/pp_tod_stack.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/axist_to_avst_bridge/ftile_ghrd_avst_axist_bridge.sv
set_global_assignment -name VERILOG_FILE ../src/custom_ip/prefetcher_ts_insert/altera_msgdma_prefetcher_ts_insert.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/pps_load_tod/pps_load_tod.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/hssi_ets_ts_adapter/hssi_ets_ts_adapter.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/glitch_free_clk_mux/glitch_free_clk_mux.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/ethernet_ptp_ip/eth_tx_timestamp_adapter/eth_tx_timestamp_adapter.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/ethernet_ptp_ip/eth_tx_dma_timestamp_req/eth_tx_dma_timestamp_req.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/ethernet_ptp_ip/eth_ts_fingerprint_compare/eth_ts_fingerprint_compare.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/ethernet_ptp_ip/eth_rx_timestamp_adapter/eth_rx_timestamp_adapter.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/eth_tod_load_off/eth_tod_load_off.v
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/conduit_splitter/tod_conduit_split.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/conduit_splitter/conduit_split.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/tx_dma_fifo.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/ts_pack.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/s10_memory.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/rx_dma_fifo.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/period_bus_sync.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/parameter_scfifo.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/packet_mux_pd_8chs.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/packet_mux.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/packet_demux_pd_8chs.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/packet_demux.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/dc_fifo_param.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/clock_bus.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/cdc_toggle_synchronizer.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/cdc_synchronizer.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/cdc_packet_fifo.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/components_8chs/cdc_avmm_sync_v2.sv
set_global_assignment -name VERILOG_FILE ../src/custom_ip/altera_msgdma/prefetcher_ts_insert/altera_msgdma_prefetcher_ts_insert.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/altera_eth_fifo_pause_ctrl_adapter/altera_eth_fifo_pause_ctrl_adapter.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/agilex_ftile_hip_adapter/ftile_hip_adapter.v
set_global_assignment -name VERILOG_FILE ../src/custom_ip/agilex_acp_adapter/agilex_axi_bridge_for_acp.v
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_ip/ack_delay_logic/ack_delay_logic.sv
set_global_assignment -name VERILOG_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/alt_reset_delay.v
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/axist_to_avst_bridge/keep2empty_v2.sv
set_global_assignment -name VERILOG_FILE ../src/intel_custom_ip/axist_to_avst_bridge/hssi_ss_delay_reg_v2.v
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/axist_to_avst_bridge/axist_to_avst_tx_mac_seg_if_v2.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/axist_to_avst_bridge/axist_to_avst_bridge_v2.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/axist_to_avst_bridge/avst_to_axist_rx_mac_seg_if_v2.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/eth_f_ptp_mtod_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/eth_f_ptp_stod_top_10g.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/intel_custom_ip/ftile_eth_tod_stack/common/eth_f_ptp_stod_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/hssi/rtl/inc/ofs_fim_eth_plat_defines.svh
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/hssi/rtl/inc/ofs_fim_eth_plat_if_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/hssi/rtl/inc/ofs_fim_eth_if_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/hssi/rtl/inc/ofs_fim_eth_if.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/hssi/rtl/inc/ofs_fim_eth_avst_if_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/hssi/rtl/inc/ofs_fim_eth_avst_if.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/hssi/rtl/lib/ofs_fim_hssi_axis_connect.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/sync/fim_resync.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/sync/fim_cross_handshake.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/sync/fim_cross_strobe.sv
set_global_assignment -name VERILOG_FILE ../src/custom_rtl/sync/altera_std_synchronizer_nocut.v
set_global_assignment -name SYSTEMVERILOG_FILE ../src/custom_rtl/hssi/ofs_fim_axi_lite_if.sv
set_global_assignment -name VERILOG_FILE ../src/custom_ip/debounce/debounce.v
set_global_assignment -name SYSTEMVERILOG_FILE ../src/top.sv
