# ######################################################################## 
# Copyright (C) 2025 Altera Corporation.
# SPDX-License-Identifier: MIT
# ######################################################################## 

# TCL File Generated by Component Editor 22.1
# Mon Feb 21 21:55:58 PST 2022
# DO NOT MODIFY


# 
# axi4lite_shim "axi4lite_shim" v1.0
#  2022.02.21.21:55:58
# 
# 

# 
# request TCL package from ACDS 22.1
# 
package require -exact qsys 22.1


# 
# module axi4lite_shim
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi4lite_shim
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axi4lite_shim
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi4lite_shim
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi4lite_shim.sv SYSTEM_VERILOG PATH axi4lite_shim.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL axi4lite_shim
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi4lite_shim.sv SYSTEM_VERILOG PATH axi4lite_shim.sv


# 
# parameters
# 
add_parameter AW INTEGER 18
set_parameter_property AW DEFAULT_VALUE 18
set_parameter_property AW DISPLAY_NAME AW
set_parameter_property AW UNITS None
set_parameter_property AW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AW AFFECTS_GENERATION false
set_parameter_property AW HDL_PARAMETER true
set_parameter_property AW EXPORT true
add_parameter DW INTEGER 64
set_parameter_property DW DEFAULT_VALUE 64
set_parameter_property DW DISPLAY_NAME DW
set_parameter_property DW UNITS None
set_parameter_property DW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DW AFFECTS_GENERATION false
set_parameter_property DW HDL_PARAMETER true
set_parameter_property DW EXPORT true
add_parameter ASYNC INTEGER 0
set_parameter_property ASYNC DEFAULT_VALUE 0
set_parameter_property ASYNC DISPLAY_NAME ASYNC
set_parameter_property ASYNC UNITS None
set_parameter_property ASYNC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ASYNC AFFECTS_GENERATION false
set_parameter_property ASYNC HDL_PARAMETER true
set_parameter_property ASYNC EXPORT true


# 
# display items
# 


# 
# connection point axi4lite_slave
# 
add_interface axi4lite_slave axi4lite end
set_interface_property axi4lite_slave associatedClock s_clock
set_interface_property axi4lite_slave associatedReset s_resetn
set_interface_property axi4lite_slave readAcceptanceCapability 1
set_interface_property axi4lite_slave writeAcceptanceCapability 1
set_interface_property axi4lite_slave combinedAcceptanceCapability 1
set_interface_property axi4lite_slave bridgesToMaster ""
set_interface_property axi4lite_slave ENABLED true
set_interface_property axi4lite_slave EXPORT_OF ""
set_interface_property axi4lite_slave PORT_NAME_MAP ""
set_interface_property axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property axi4lite_slave SVD_ADDRESS_GROUP ""
set_interface_property axi4lite_slave IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port axi4lite_slave s_awaddr awaddr Input "((AW - 1)) - (0) + 1"
add_interface_port axi4lite_slave s_awprot awprot Input 3
add_interface_port axi4lite_slave s_awvalid awvalid Input 1
add_interface_port axi4lite_slave s_awready awready Output 1
add_interface_port axi4lite_slave s_wdata wdata Input "((DW - 1)) - (0) + 1"
add_interface_port axi4lite_slave s_wstrb wstrb Input "(((DW / 8) - 1)) - (0) + 1"
add_interface_port axi4lite_slave s_wvalid wvalid Input 1
add_interface_port axi4lite_slave s_wready wready Output 1
add_interface_port axi4lite_slave s_bresp bresp Output 2
add_interface_port axi4lite_slave s_bvalid bvalid Output 1
add_interface_port axi4lite_slave s_bready bready Input 1
add_interface_port axi4lite_slave s_araddr araddr Input "((AW - 1)) - (0) + 1"
add_interface_port axi4lite_slave s_arprot arprot Input 3
add_interface_port axi4lite_slave s_arvalid arvalid Input 1
add_interface_port axi4lite_slave s_arready arready Output 1
add_interface_port axi4lite_slave s_rdata rdata Output "((DW - 1)) - (0) + 1"
add_interface_port axi4lite_slave s_rresp rresp Output 2
add_interface_port axi4lite_slave s_rvalid rvalid Output 1
add_interface_port axi4lite_slave s_rready rready Input 1


# 
# connection point axi4lite_master
# 
add_interface axi4lite_master axi4lite start
set_interface_property axi4lite_master associatedClock m_clock
set_interface_property axi4lite_master associatedReset m_resetn
set_interface_property axi4lite_master readIssuingCapability 1
set_interface_property axi4lite_master writeIssuingCapability 1
set_interface_property axi4lite_master combinedIssuingCapability 1
set_interface_property axi4lite_master ENABLED true
set_interface_property axi4lite_master EXPORT_OF ""
set_interface_property axi4lite_master PORT_NAME_MAP ""
set_interface_property axi4lite_master CMSIS_SVD_VARIABLES ""
set_interface_property axi4lite_master SVD_ADDRESS_GROUP ""
set_interface_property axi4lite_master IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port axi4lite_master m_awaddr awaddr Output "((AW - 1)) - (0) + 1"
add_interface_port axi4lite_master m_awprot awprot Output 3
add_interface_port axi4lite_master m_awvalid awvalid Output 1
add_interface_port axi4lite_master m_awready awready Input 1
add_interface_port axi4lite_master m_wdata wdata Output "((DW - 1)) - (0) + 1"
add_interface_port axi4lite_master m_wstrb wstrb Output "(((DW / 8) - 1)) - (0) + 1"
add_interface_port axi4lite_master m_wvalid wvalid Output 1
add_interface_port axi4lite_master m_wready wready Input 1
add_interface_port axi4lite_master m_bresp bresp Input 2
add_interface_port axi4lite_master m_bvalid bvalid Input 1
add_interface_port axi4lite_master m_bready bready Output 1
add_interface_port axi4lite_master m_araddr araddr Output "((AW - 1)) - (0) + 1"
add_interface_port axi4lite_master m_arprot arprot Output 3
add_interface_port axi4lite_master m_arvalid arvalid Output 1
add_interface_port axi4lite_master m_arready arready Input 1
add_interface_port axi4lite_master m_rdata rdata Input "((DW - 1)) - (0) + 1"
add_interface_port axi4lite_master m_rresp rresp Input 2
add_interface_port axi4lite_master m_rvalid rvalid Input 1
add_interface_port axi4lite_master m_rready rready Output 1


# 
# connection point s_clock
# 
add_interface s_clock clock end
set_interface_property s_clock ENABLED true
set_interface_property s_clock EXPORT_OF ""
set_interface_property s_clock PORT_NAME_MAP ""
set_interface_property s_clock CMSIS_SVD_VARIABLES ""
set_interface_property s_clock SVD_ADDRESS_GROUP ""
set_interface_property s_clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port s_clock s_clk clk Input 1


# 
# connection point m_clock
# 
add_interface m_clock clock end
set_interface_property m_clock ENABLED true
set_interface_property m_clock EXPORT_OF ""
set_interface_property m_clock PORT_NAME_MAP ""
set_interface_property m_clock CMSIS_SVD_VARIABLES ""
set_interface_property m_clock SVD_ADDRESS_GROUP ""
set_interface_property m_clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port m_clock m_clk clk Input 1


# 
# connection point s_resetn
# 
add_interface s_resetn reset end
set_interface_property s_resetn associatedClock s_clock
set_interface_property s_resetn synchronousEdges DEASSERT
set_interface_property s_resetn ENABLED true
set_interface_property s_resetn EXPORT_OF ""
set_interface_property s_resetn PORT_NAME_MAP ""
set_interface_property s_resetn CMSIS_SVD_VARIABLES ""
set_interface_property s_resetn SVD_ADDRESS_GROUP ""
set_interface_property s_resetn IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port s_resetn s_rst_n reset_n Input 1


# 
# connection point m_resetn
# 
add_interface m_resetn reset end
set_interface_property m_resetn associatedClock m_clock
set_interface_property m_resetn synchronousEdges DEASSERT
set_interface_property m_resetn ENABLED true
set_interface_property m_resetn EXPORT_OF ""
set_interface_property m_resetn PORT_NAME_MAP ""
set_interface_property m_resetn CMSIS_SVD_VARIABLES ""
set_interface_property m_resetn SVD_ADDRESS_GROUP ""
set_interface_property m_resetn IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port m_resetn m_rst_n reset_n Input 1

